from os.path import join
import os,inspect

CURRENT_DIRNAME = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
PARENT_DIRNAME = os.path.dirname(CURRENT_DIRNAME)

DATASET_DIRNAME = 'dataset'
ORIGINAL_DATA_DIRNAME = 'original'
IMAGE_DIRNAME = 'image'
TRAIN_DIR_NAME = 'train_set'
VAL_DIR_NAME = 'val_set'
TEST_DIR_NAME = 'test_set'

DATASET_DIR_PATH = join(CURRENT_DIRNAME,DATASET_DIRNAME)

ORIGINAL_DATA_PATH = join(DATASET_DIR_PATH,ORIGINAL_DATA_DIRNAME)
IMAGE_DATA_PATH = join(DATASET_DIR_PATH,IMAGE_DIRNAME)

TRAIN_DATA_DIR_PATH = join(DATASET_DIR_PATH,TRAIN_DIR_NAME)
VAL_DATA_DIR_PATH = join(DATASET_DIR_PATH,VAL_DIR_NAME)
TEST_DATA_DIR_PATH = join(DATASET_DIR_PATH,TEST_DIR_NAME)

MODEL_DIRNAME = 'model'
MODEL_DIR_PATH = join(CURRENT_DIRNAME,MODEL_DIRNAME)