from os.path import join
import os,sys,inspect

CURRENT_DIRNAME = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
PARENT_DIRNAME = os.path.dirname(CURRENT_DIRNAME)
#sys.path.insert(0,PARENT_DIRNAME) 

DATASET_DIRNAME = 'dataset'
ORIGINAL_DATA_DIRNAME = 'original'
PREPARED_DATA_DIRNAME = 'prepared_data'
FILE_PROCESSED_DIRNAME = 'file_processed'
IMAGE_DIRNAME = 'image'

DATASET_DIR_PATH = join(CURRENT_DIRNAME,DATASET_DIRNAME)
PREPARED_DATA_PATH = join(DATASET_DIR_PATH,PREPARED_DATA_DIRNAME)
FILE_PROCESSED_PATH = join(DATASET_DIR_PATH,FILE_PROCESSED_DIRNAME)
ORIGINAL_DATA_PATH = join(DATASET_DIR_PATH,ORIGINAL_DATA_DIRNAME)
IMAGE_DATA_PATH = join(DATASET_DIR_PATH,IMAGE_DIRNAME)

TRAIN_DIR_NAME = 'train_set'
TRAIN_DATA_DIR_PATH = join(DATASET_DIR_PATH,TRAIN_DIR_NAME)
VAL_DIR_NAME = 'val_set'
VAL_DATA_DIR_PATH = join(DATASET_DIR_PATH,VAL_DIR_NAME)
TEST_DIR_NAME = 'test_set'
TEST_DATA_DIR_PATH = join(DATASET_DIR_PATH,TEST_DIR_NAME)


MODEL_DIRNAME = 'model'
MODEL_DIR_PATH = join(CURRENT_DIRNAME,MODEL_DIRNAME)